@api=http://localhost:5000
@id=614f7d1d01142632f3d4593d
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNGJjZDgyODUxNDhkOGI4MTQ1ODg2NyIsIm5hbWUiOiJSZW56byIsImlhdCI6MTYzMjU5OTcxNSwiZXhwIjoxNjMyNjg2MTE1fQ.7VjnZJRpHx7G5wbVhxZCcM1iEX2NrcsTgLZ3uBrbbvE

### Add book to db
POST {{api}}/api/book
Content-Type: application/json

{
    "title": "Whatetefac",
	"author": "renzo",
	"year": 1994,
	"status": "to be read"
}

### get all the books of the user id
GET {{api}}/api/book/{{id}}


### Update a book
PUT {{api}}/api/book/{{id}}
Content-Type:application/json
Authorization: Bearer @{{token}}

{
    "title": "sdsd"
}

### Delete Book by id
DELETE {{api}}/api/book/{{id}} 
Content-Type:application/json
Authorization:Bearer @{{token}}

